jwt:
    time: 900000546321
    secret: hello-world423145

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
