spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: "{cipher}a255a2b23c64393c1b1dbdefe45e79de1e506480691dc890dc6969cd72138eed"
jwt:
    secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
    expTime: 86400000
