jwt:
    time: 900000
    secret: hello-world4444

test:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
