my-config.name: defualt update 키키키

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

management:
    endpoints:
        web:
            exposure:
                include: refresh, health, beans, busrefresh
    endpoint:
        shutdown:
            enabled: true
    security:
        enabled: false
